version: 2

jobs:
  build:
    working_directory: /go/src/github.com/vvakame/go-harlog
    docker:
      - image: golang:1.13.1
    environment:
      GO111MODULE: "on"
    steps:
      - checkout:
          path: /go/src/github.com/vvakame/go-harlog
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: test
          command: |
            ./setup.sh
            ./test.sh -v
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
